param(
  [Parameter(Mandatory=$true)][string]$SourceRunRoot,
  [Parameter(Mandatory=$true)][string]$OutputRoot
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$ProgressPreference='SilentlyContinue'

if ([string]::IsNullOrWhiteSpace($env:MESHY_API_KEY)) { throw 'MESHY_API_KEY missing.' }

$Api='https://api.meshy.ai'
$Headers=@{ Authorization="Bearer $($env:MESHY_API_KEY)"; 'Content-Type'='application/json' }
$ModelsDir=Join-Path $OutputRoot 'models'
$ReportsDir=Join-Path $OutputRoot 'reports'
New-Item -ItemType Directory -Force -Path $ModelsDir,$ReportsDir | Out-Null

function Log([string]$m){ $l="[$((Get-Date).ToString('HH:mm:ss'))] $m"; Write-Host $l; Add-Content -LiteralPath (Join-Path $ReportsDir 'resume.log') -Value $l -Encoding UTF8 }
function Invoke-Meshy([string]$Method,[string]$Path,$Body=$null){
  $uri="$Api$Path"
  if($null -eq $Body){ return Invoke-RestMethod -Method $Method -Uri $uri -Headers $Headers -TimeoutSec 120 }
  $json=$Body|ConvertTo-Json -Depth 10 -Compress
  return Invoke-RestMethod -Method $Method -Uri $uri -Headers $Headers -Body $json -TimeoutSec 120
}
function Wait-Task([string]$Path,[string]$Id,[int]$TimeoutSec=2400){
  $deadline=(Get-Date).AddSeconds($TimeoutSec)
  while((Get-Date)-lt $deadline){
    $t=Invoke-Meshy 'GET' "$Path/$Id"
    Write-Host "  $Id status=$($t.status) progress=$($t.progress)"
    if($t.status -eq 'SUCCEEDED'){ return $t }
    if($t.status -eq 'FAILED'){ throw "Meshy task failed: $Id :: $($t.task_error.message)" }
    Start-Sleep -Seconds 6
  }
  throw "Meshy timeout: $Id"
}
function Download-Model($Task,[string]$Name){
  foreach($ext in @('glb','fbx')){
    $u=$Task.model_urls.$ext
    if($u){ Invoke-WebRequest -UseBasicParsing -Uri $u -OutFile (Join-Path $ModelsDir "$Name.$ext") -TimeoutSec 300 }
  }
}
function Get-Balance { try { return [int](Invoke-Meshy 'GET' '/openapi/v1/balance').balance } catch { return -1 } }
function Find-LocalExisting([string[]]$Patterns){
  $roots=@('D:\AetherqorPipeline','D:\Aetherfall - Realms of the Veil') | Where-Object { Test-Path -LiteralPath $_ }
  foreach($root in $roots){
    foreach($p in $Patterns){
      $f=Get-ChildItem -LiteralPath $root -Recurse -File -Filter $p -ErrorAction SilentlyContinue | Where-Object { $_.Extension -ieq '.glb' } | Sort-Object LastWriteTime -Descending | Select-Object -First 1
      if($f){ return $f.FullName }
    }
  }
  return $null
}

# Reuse everything already generated by the current run.
$srcGen=Join-Path $SourceRunRoot 'generated'
$srcModels=Join-Path $srcGen 'models'
if(Test-Path -LiteralPath $srcModels){
  Log "Reusing generated files from $srcModels"
  Get-ChildItem -LiteralPath $srcModels -File -ErrorAction SilentlyContinue | Copy-Item -Destination $ModelsDir -Force
}

# Never keep jewellery from the mistaken interpretation.
foreach($n in @('Ring_L','Ring_R','Necklace','Bracelet')){
  Get-ChildItem -LiteralPath $ModelsDir -File -ErrorAction SilentlyContinue | Where-Object { $_.BaseName -eq $n } | Remove-Item -Force -ErrorAction SilentlyContinue
}

# Reuse exact existing Runic Warden weapon assets before any Meshy call.
if(-not (Test-Path -LiteralPath (Join-Path $ModelsDir 'Sword.glb'))){
  $p=Find-LocalExisting @('*RunicWarden*Oathblade*.glb','*Oathblade*Standard*3D*.glb')
  if($p){ Copy-Item -LiteralPath $p -Destination (Join-Path $ModelsDir 'Sword.glb') -Force; Log "REUSE Sword from $p" }
}
if(-not (Test-Path -LiteralPath (Join-Path $ModelsDir 'Shield.glb'))){
  $p=Find-LocalExisting @('*RunicWarden*AegisShield*.glb','*AegisShield*Standard*3D*.glb')
  if($p){ Copy-Item -LiteralPath $p -Destination (Join-Path $ModelsDir 'Shield.glb') -Force; Log "REUSE Shield from $p" }
}

# Rig is mandatory. If body exists but rig does not, rig only. Never regenerate body if Body_Base already exists.
$bodyRigged=Join-Path $ModelsDir 'Body_Rigged.glb'
$bodyBase=Join-Path $ModelsDir 'Body_Base.glb'
if(-not (Test-Path -LiteralPath $bodyRigged)){
  if(-not (Test-Path -LiteralPath $bodyBase)){ throw 'Body_Base.glb missing. Resume refuses to regenerate body automatically.' }
  Log 'Body_Rigged missing. Searching previous Meshy task metadata for body task id.'
  $taskJson=Join-Path $srcGen 'reports\meshy_tasks.json'
  if(-not (Test-Path -LiteralPath $taskJson)){ throw 'Cannot rig without existing body Meshy task id. No meshy_tasks.json found.' }
  $tasks=Get-Content -LiteralPath $taskJson -Raw | ConvertFrom-Json
  $bodyTask=$tasks | Where-Object { $_.name -eq 'Body' -and $_.phase -eq 'image-to-3d' } | Select-Object -First 1
  if(-not $bodyTask){ throw 'Body image-to-3d task id not found in previous report.' }
  $rc=Invoke-Meshy 'POST' '/openapi/v1/rigging' @{ input_task_id=$bodyTask.id; height_meters=1.78 }
  $rig=Wait-Task '/openapi/v1/rigging' $rc.result 1800
  if($rig.result.rigged_character_glb_url){ Invoke-WebRequest -UseBasicParsing -Uri $rig.result.rigged_character_glb_url -OutFile $bodyRigged -TimeoutSec 300 }
  if($rig.result.rigged_character_fbx_url){ Invoke-WebRequest -UseBasicParsing -Uri $rig.result.rigged_character_fbx_url -OutFile (Join-Path $ModelsDir 'Body_Rigged.fbx') -TimeoutSec 300 }
}
if(-not (Test-Path -LiteralPath $bodyRigged)){ throw 'Rigged body still missing after resume.' }

$common='Standalone wearable game asset for an athletic adult male 1.78m dark-fantasy Runic Warden. Realistic PBR, forged blackened iron, dark steel, restrained oxidized old-gold/brass trim, engraved geometric runes with subtle warm amber-white glow, premium battle-worn detail, clean silhouette, no blue, no text, no logo, no watermark, no body, no mannequin, centered at origin, front facing, production game asset.'
$core=@(
 @{N='Helmet';P=2200;Q="$common Closed/open-face knight helmet, fitted human head proportions, strong brow, modest rune crest, neck clearance, no giant horns."},
 @{N='ChestArmor';P=4200;Q="$common Rigid torso breastplate shell with front and back plates, open neck and armholes, fitted waist, layered abdominal plates, no body inside."},
 @{N='Shoulders';P=2200;Q="$common Matching pair of moderate left and right shoulder pauldrons as two disconnected pieces, not oversized, articulated lower lames."},
 @{N='Gloves';P=1800;Q="$common Matching pair of armored gauntlets as two disconnected pieces, open wrist cuffs, articulated fingers, practical proportions."},
 @{N='Belt';P=1200;Q="$common Armored waist belt, oval human waist opening, segmented dark leather and metal, central runic clasp, no hanging body."},
 @{N='Legs';P=3200;Q="$common Leg armor garment: fitted armored trousers/tassets covering pelvis and thighs to below knees, open waist and leg openings, symmetrical."},
 @{N='Boots';P=1800;Q="$common Matching pair armored boots as two disconnected pieces, solid sole, clear heel and toe volume, shin guards, not slippers."},
 @{N='Cloak';P=2200;Q="$common Heavy dark charcoal back cloak for a warrior, shoulder attachment points, split lower hem, subtle old-gold rune border, hanging vertically, no body."},
 @{N='Sword';P=2400;Q="$common One-handed/hand-and-a-half runic longsword, straight forged blade, practical hilt and grip, warm amber rune engraving, isolated weapon."},
 @{N='Shield';P=2600;Q="$common Medium runic knight shield, convex dark iron, reinforced old-gold rim, central geometric ward sigil, rear grip implied, isolated shield."},
 @{N='ClassRelic';P=1200;Q="$common Compact Runic Warden class relic: palm-sized ward stone in forged dark metal cage, geometric rune, subtle warm amber-white energy, attachable to chest or belt."}
)

$generated=@()
$reused=@()
foreach($g in $core){
  $dst=Join-Path $ModelsDir "$($g.N).glb"
  if(Test-Path -LiteralPath $dst){ Log "SKIP existing $($g.N)"; $reused += $g.N; continue }
  $bal=Get-Balance
  if($bal -ge 0 -and $bal -lt 25){ throw "Meshy balance too low before $($g.N): $bal" }
  Log "GENERATE missing core slot $($g.N)"
  $pc=Invoke-Meshy 'POST' '/openapi/v2/text-to-3d' @{ mode='preview'; model_type='standard'; ai_model='latest'; prompt=$g.Q; should_remesh=$true; topology='quad'; target_polycount=$g.P; target_formats=@('glb','fbx'); auto_size=$false }
  $preview=Wait-Task '/openapi/v2/text-to-3d' $pc.result 2400
  $rc=Invoke-Meshy 'POST' '/openapi/v2/text-to-3d' @{ mode='refine'; preview_task_id=$preview.id; enable_pbr=$true; texture_resolution='4k'; remove_lighting=$true; target_formats=@('glb','fbx') }
  $refined=Wait-Task '/openapi/v2/text-to-3d' $rc.result 2400
  Download-Model $refined $g.N
  $generated += $g.N
}

$required=@('Body_Rigged','Helmet','ChestArmor','Shoulders','Gloves','Belt','Legs','Boots','Cloak','Sword','Shield','ClassRelic')
$missing=@()
foreach($n in $required){ if(-not (Test-Path -LiteralPath (Join-Path $ModelsDir "$n.glb"))){ $missing += $n } }
$summary=[ordered]@{ source_run=$SourceRunRoot; output_root=$OutputRoot; generated=$generated; reused=$reused; missing=$missing; jewellery_excluded=@('Ring_L','Ring_R','Necklace','Bracelet'); rig_required=$true; balance_end=(Get-Balance) }
$summary|ConvertTo-Json -Depth 6|Set-Content -LiteralPath (Join-Path $ReportsDir 'resume_summary.json') -Encoding UTF8
if($missing.Count -gt 0){ throw "Missing required core assets after resume: $($missing -join ', ')" }
Log 'CORE_ONLY_RESUME_DONE'
